### ISSUE TITLE
browsing scraps

### ISSUE THREAD

**Issue by fogfx** [wix-incubator/DeviantArt-API#126]
Is there a way to browse/include a user's scraps? I could have sworn the `/gallery` endpoint, without specifying `folderid` and sorted 'newest', included scraps maybe a year or so ago; having tested a few users on the front page (that do have scraps), though, scraps no longer appear to be included in the retrieved submissions.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
