### ISSUE TITLE
deviation object - add Views to stats

### ISSUE THREAD

**Issue by Algogator** [wix-incubator/DeviantArt-API#129]
Consider adding views to the stats object

**Comment by exzizt** [comment]
Wow! I just opened an issue about this without seeing this first. Yes--please do this. Same as the "downloads" stat. Might as well. Currently, the only way to get this information is via the hacky method of links like [this](https://backend.deviantart.com/oembed?url=http%3A%2F%2Ffav.me%2Fdcnfohf&format=json).

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
