### ISSUE TITLE
Adopts

### ISSUE THREAD

**Issue by SSF1313** [wix-incubator/DeviantArt-API#131]
Hi, I recently made a couple of outfit adopts use my Polyvore account, when some came and accused me of stealing. I explained what I did and how I made them. They came back, and said that I didn't make them and that they didn't count, and that they had to be drawn. I'd like to know if I am allowed to make adopts using polyvore, with the proper crediting.

**Comment by aaronpearce** [comment]
Closing as this is irrelevant to this GitHub project.
