### ISSUE TITLE
Remove deviations from Watch feed

### ISSUE THREAD

**Issue by franckyg** [wix-incubator/DeviantArt-API#132]
Hi,
I'm retrieving new deviations from /home/feed but i didn't find how to remove them. Is there any POST request to do this ?

Thanks
Franck

**Comment by Viachaslau-Zinkevich** [comment]
As far as I know, this is actually meant like twitter/facebook feed. In the meaning that you can't delete deviations

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
