### ISSUE TITLE
/user/friends/watching/{username} endpoint documentation says "Check if :username: is watching you" when it's actually the other way around

### ISSUE THREAD

**Issue by theothersophie** [wix-incubator/DeviantArt-API#140]
Can we get an API endpoint for what it actually says? Check if :username: is watching you.

**Comment by cesarblancg** [comment]
up.

The only solution I can thing about is use the API endpoint /user/friends/search.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
