### ISSUE TITLE
sta.sh/deviantart image name schema question

### ISSUE THREAD

**Issue by SomewhatDamaged** [wix-incubator/DeviantArt-API#144]
I managed (after a lot of searching) to find the schema used for regular DA images:

```
{title}_by_{artist}-d{code(base 10)}.*
https://{artist(_ turned into -)}.deviantart.com/art/{title(_ turned into -)}-{code(base 36)}
```

But I have not managed to find a way to turn sta.sh image names back into a sta.sh url.

```
{title}_by_{artist}-d{code(base 10)}.*
https://sta.sh/???
```

It would be really great if both these schema/conversions were listed in the API area. My reason for using this is for a lookup to find original pages from images dropped directly into a modern chat system (Discord) so that the art's correct page is listed.

**Comment by KarsonKimbrel** [comment]
This is a use case that DA's oEmbed API would come in handy for. https://www.deviantart.com/developers/oembed

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
