### ISSUE TITLE
Getting list of gallery folders by folderid

### ISSUE THREAD

**Issue by yevhen-kutishchev** [wix-incubator/DeviantArt-API#146]
Folders in gallery can have tree structure (for core members). If I want to display content of some nested folder then I need load list of all folders using `/gallery/folders` end-point and then filter that list by folder id. But it gets very inconvenient if user has more folders then it's possible to get with one request. In that case I will have to make multiple requests to fetch all folders. I understand that it's unlikely that user will have more than 50 folders but still it can happen.
So my question is it possible in some near future to implement end-point (for example `/gallery/folders/{folderid}`) that will return folders inside specified `folderid`?

**Comment by Foze123** [comment]
Anyone can answer , how we can fix the issue of this case ?

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
