### ISSUE TITLE
Implement Way To Access A Deviant's "Views" Attribute

### ISSUE THREAD

**Issue by exzizt** [wix-incubator/DeviantArt-API#151]
There is no way to do this currently with the API.

Doing "/deviation/{deviationid}" or "/gallery/{galleryid}", for example, only returns the statistics of comments and favourites:

"stats": {

"comments": 0,
"favourites": 2
}

I would think that views are a very important statistic for a deviation, and they should definitely be included in the stats object.

Currently, the only way to get the views count (and some other attributes not included normally in the API) is to use the hacky way of a link like this (can be retrieved from a deviation's page by viewing source), for example:
https://backend.deviantart.com/oembed?url=http%3A%2F%2Ffav.me%2Fdcnfohf&format=json

But, this is not desirable, as you have to make multiple requests to these links if you want these stats for many deviations. There, you can get more stats like views and downloads count as well which is very useful.

Please consider implementing this!

**Comment by karma12gaming** [comment]
I would love a feature like this as well.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
