### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by dalf** [wix-incubator/DeviantArt-API#157]
At least one query ```香港``` returns an invalid XML:
https://backend.deviantart.com/rss.xml?type=deviation&q=%E9%A6%99%E6%B8%AF&0

Another one with ```東京``` says "Error generating RSS." in the description :
https://backend.deviantart.com/rss.xml?type=deviation&q=%E6%9D%B1%E4%BA%AC&0

It seems there are problem with encoding.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
