### ISSUE TITLE
Document about OAuth scope parameter

### ISSUE THREAD

**Issue by Naeemo** [wix-incubator/DeviantArt-API#158]
Here is some document about the `scope` parameter from lately experience. 
1. Generally, scope is the first word of endpoint's url, like `/gallery/folders`'s scope is `gallery`. Here is a rough list:
- `basic`
- `user`
- `collection` (instead of collections)
- `browse`
- `gallery`
……

2. Multiple scope should be separated by space, thanks to #17
Example: `&scope=basic user` 

It would be great if you guys can add more detail docs about it on the website.

**Comment by Neko3000** [comment]
I'm working on this very same problem.
Thank your comment sincerely, which saved me from getting various tokens with different types.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
