### ISSUE TITLE
/api/v1/oauth2/collections/ - triggers has_more: False too soon

### ISSUE THREAD

**Issue by Archirk** [wix-incubator/DeviantArt-API#164]
Hello
I try to get all deviations objects from collection with cycle until i get a response with  'has_more: False'
collection BE8DB4CE-21DD-4F16-55AE-9724A5E9F8EE,
username: ladyhedgie
'mature_content': True, limit: 24

But in this case i get only 5089 objects instead of 5714. and it is consistent number.
I checked: cycle stops because at 5089 offset  method returns 'has_more: False'
In dev-console on your site it [returns True.](https://www.deviantart.com/developers/console/collections/collections/834f7f78540bc3b092f1876bbae30869?url%3Afolderid=BE8DB4CE-21DD-4F16-55AE-9724A5E9F8EE&username=ladyhedgie&offset=5089&limit=24&da_version=&expand=&grant_type=client_credentials&mature_content=true&endpoint=%2Fcollections%2F%7Bfolderid%7D) 
So i do not understand what is happening.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
