### ISSUE TITLE
openssl 1.1.1 problem

### ISSUE THREAD

**Issue by pearlydragon** [wix-incubator/DeviantArt-API#165]
Hi.
I don't really know where write about problem, but I have next problem with deviantart.com:
browsers doesn't connect to site.

`curl -vL https://www.deviantart.com/
*   Trying 54.230.231.99...
* TCP_NODELAY set
* Connected to www.deviantart.com (54.230.231.99) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.deviantart.com:443 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.deviantart.com:443 `

and
`openssl s_client -connect www.deviantart.com:443 -tls1_2
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 176 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1572951596
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---`

I tried find solution, and found next: "You need to configure OpenSSL with “enable-weak-ssl-ciphers”"

As I understand site use old ciphers, what has been deprecated in new openssl. In new versions of the OS we have openssl v1.1 or newer, and we can't open site without rebuild openssl from sources with support weak ciphers. And it's problem have place around few months.
Other popular sites has been upgraded for new standards, but not deviantart.

**Comment by pearlydragon** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=www.deviantart.com&s=99.84.237.64&latest

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
