### ISSUE TITLE
Literature Deviation text cut

### ISSUE THREAD

**Issue by abdoulayeYATERA** [wix-incubator/DeviantArt-API#167]
Hi there,
Literature deviations text content is cut.
It's like there is a max characters number on it.
Server response example :
~~~
{
    "deviationid": "9FA59ECC-01AE-2908-FC37-2F9763D70337",
    "printid": null,
    "url": "https://www.deviantart.com/mutitus/art/Eldegoss-Report-825442476",
    "title": "Eldegoss Report",
    "category": "Profiles",
    "category_path": "literature/characters/scifi/profiles",
    "is_favourited": false,
    "is_deleted": false,
    "author": {
        "userid": "8E20B87B-61FE-612E-ED16-FBB93D8C183B",
        "username": "Mutitus",
        "usericon": "https://a.deviantart.net/avatars/m/u/mutitus.png?6",
        "type": "regular"
    },
    "stats": {
        "comments": 0,
        "favourites": 8
    },
    "published_time": "1577891369",
    "allows_comments": true,
    "thumbs": [],
    "excerpt": "Eldegoss (the Cotton Bloom Pok&#233;mon) is an uncommon Grass-type Pok&#233;mon found in grassy fields within the Galar region. Gorgeous in appearance and elegant in their motions, Eldegoss are simple but fun plants that can definitely perk up those that are feeling tired or lonely. They might not have much to speak of when it comes to feats of strength, but these plants can still prove to be quite the defensive trouble in the right cases&#8230;especially if one accidentally inhales part of their head!<br /><br />When Gossifleur evolve into Eldegoss, the blooming flower on their heads finally gives way to a massive pod of seeds, and in their case, thes",
    "is_mature": false,
    "is_downloadable": false
}
~~~
We can see that excerpt content is cut and does not contain the full text that we see on the web page https://www.deviantart.com/mutitus/art/Eldegoss-Report-825442476

Reproduced on those apis (didn't test on others) : 
/deviation/{deviationid}
/browse/popular

**Comment by bloodywing** [comment]
You can try to get the full content with another endpoint: `/deviation/content` is intended for this.

**Comment by abdoulayeYATERA** [comment]
Hi @bloodywing !
Ok i see, that cost one extra request per literature deviation though.
I guess there is no solution to have the full content within the deviation object at the moment.
I'll see what I can do with that.
Thanks !

**Comment by aaronpearce** [comment]
Hi,

To retrieve a literature deviation's full content you will need to call `/deviation/content`. This is to save resources in the API as literatures/journals can be large in size to return directly in a feed API.
