### ISSUE TITLE
API to Obtain List of Members Watched by (Current) User

### ISSUE THREAD

**Issue by chaoscommencer** [wix-incubator/DeviantArt-API#168]
[Feature Request]
As a user, it would be nice to be able to view the list of members you are watching.

The API currently supports obtaining a list of the user's friends:
GET /user/friends/{username}

But it lacks support for obtaining the list of artists the user watches, instead only providing access to the list of members watching them.

**Comment by chaoscommencer** [comment]
Just discovered that though the documentation doesn't describe this, it appears the following API call does obtain the list of members watched by the current user:

GET /user/friends/{username}

This feature request should be changed to a documentation update.

Thanks!

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
