### ISSUE TITLE
Revoke Access Token Error

### ISSUE THREAD

**Issue by chaoscommencer** [wix-incubator/DeviantArt-API#169]
[Bug]?
Most of the calls I make against the API work as expected; however, when attempting to revoke an access token in order to close out a session, DeviantArt returns Error 302.

Following the documentation, I have tried all variations I can think of, including the following:

POST https://www.deviantart.com/oauth2/revoke?token=...&revoke_refresh_only=true
POST https://www.deviantart.com/oauth2/revoke?access_token=...&revoke_refresh_only=true
POST https://www.deviantart.com/oauth2/revoke?token=...&access_token=...&revoke_refresh_only=true
POST https://www.deviantart.com/oauth2/revoke?token=...
POST https://www.deviantart.com/oauth2/revoke?access_token=...
POST https://www.deviantart.com/oauth2/revoke?token=...&access_token=...

(of course replacing the "..." portions with the actual token)

I've also tried the above with PUT and GET calls to the same effect.

I am wondering if the error I am seeing is the result of a bug in the API or whether I'm missing something that's perhaps not documented?

Any help/suggestions/patches would be greatly appreciated!

Thanks!

EDIT: After further investigation it appears the issue relates to inadequacies in the parsing of request data (formatted with the "application/json" content type).  A workaround involves formatting the request data according to the "application/x-www-form-urlencoded" content type instead.  A proper fix for this bug would be great though!

**Comment by bloodywing** [comment]
http status code 302 isn't an error as far as I know.
https://www.oauth.com/oauth2-servers/authorization/the-authorization-response/

**Comment by chaoscommencer** [comment]
Here are some more details that suggest it isn't working appropriately:


Request

POST https://www.deviantart.com/oauth2/revoke?token=<token_here>&revoke_refresh_only=true


Response

QNetworkReply::ProtocolInvalidOperationError (302)
"Error transferring https://www.deviantart.com/oauth2/revoke?token=<token_here>&revoke_refresh_only=true - server replied: Bad Request" 
```
(
    QPair("Content-Type","application/json; charset=utf-8"),
    QPair("Connection","keep-alive"),
    QPair("Date","Sat, 18 Jan 2020 05:59:38 GMT"),
    QPair("Server","Apache"),
    QPair("Cache-Control","Private, no-cache, no-store, must-revalidate, max-age=0, max-stale=0, post-check=0, pre-check=0"),
    QPair("Pragma","no-cache"),
    QPair("Expires","0"),
    QPair("Content-Encoding","gzip"),
    QPair("Vary","Accept-Encoding"),
    QPair("X-Backend","web_http_back"),
    QPair("X-Cache","Error from cloudfront"),
    QPair("Via","1.1 <hex_code>.cloudfront.net (CloudFront)"),
    QPair("X-Amz-Cf-Pop","<other_value>"),
    QPair("X-Amz-Cf-Id","<encoded_value>")
)
```

```
{
    "error":"invalid_request",
    "error_description":"Request field validation failed.",
    "error_details":
    {
        "token":"token is required"
    },
    "status":"error"
}
```

_NOTE:
<token_here> is a token value
<hex_code> is a hex code
<encoded_value> is an encoded value_

The "error_details" field appears to suggest that a token wasn't passed to the POST request, even though it can be seen in request URL query.

**Comment by bloodywing** [comment]
token=xxx is a post field and shouldn't go into your url parameters.

**Comment by chaoscommencer** [comment]
Thanks for your help; I actually tried passing the arguments by that method first.  Just spent a few more hours on it and seem to have discovered the heart of the bug,

The API is not properly parsing POST requests with JSON-formatted content (even when the content type header is set to "application/json").  However, it does seem to work correctly for content formatted like a url query (with content type header "application/x-www-form-urlencoded").

**Comment by bloodywing** [comment]
This isn't a bug, it's the RFC

https://tools.ietf.org/html/rfc7009#section-2.1 it's intended that it only works with x-www-form-urlencoded.

**Comment by chaoscommencer** [comment]
Thanks.  Interesting caveat.  Might be a good idea to note that in the DeviantArt API documentation, since "application/json" is a fairly common default format for passing parameters.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
