### ISSUE TITLE
Collections 500 error

### ISSUE THREAD

**Issue by caggles** [wix-incubator/DeviantArt-API#170]
I'm getting a 500 error when I try to hit various collections. "Internal Server Error" doesn't tell me much about what I might be doing wrong.

Example endpoint: https://www.deviantart.com/api/v1/oauth2/collections/9F04D2F1-4111-120C-D4B7-0B20E85F4168

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
