### ISSUE TITLE
Null User Object in Result for Get Friends Request

### ISSUE THREAD

**Issue by chaoscommencer** [wix-incubator/DeviantArt-API#171]
Calling
GET /user/friends/{username}
results in several "results" array entries that contain no user object.
This conflicts with the documentation which suggests the "user" field is mandatory and cannot be null.
Here is an example of one such invalid result:

https://www.deviantart.com/api/v1/oauth2/user/friends?access_token=<...access_token...>&expand=user.details,user.geo,user.profile,user.stats&limit=50&mature_content=true&offset=0

```
{
    "is_watching":true,
    "lastvisit":null,
    "user":null,
    "watch": 
    {
        "activity":true,
        "collections":true,
        "critiques":true,
        "deviations":true,
        "forum_threads":true,
        "friend":true,
        "journals":true,
        "scraps":false
    },
    "watches_you":false
}
```

**Comment by chaoscommencer** [comment]
After some investigation, this appears to happen at least for some users who've had user name changes.  I noticed there was an entry with a null user object both where an object with their old username should've been and where an object with their new username should've been, making their accounts completely inaccessible.

**Comment by chaoscommencer** [comment]
I can list some of the users who aren't showing up if desired, but am not doing so without permission for privacy concerns.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
