### ISSUE TITLE
mature_content=false Still returns mature content

### ISSUE THREAD

**Issue by cannoness** [wix-incubator/DeviantArt-API#175]
Example:
https://www.deviantart.com/developers/console/gallery/gallery_all/bdb19761e6debcc6609356d6b78f4a5d?username=shiniez&offset=&limit=&da_version=&grant_type=authorization_code&mature_content=false&endpoint=%2Fgallery%2Fall

I expect to get results with no results containing is_mature=true; however my results included these deviations as well as those with is_mature=false.

Thanks!

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
