### ISSUE TITLE
HTTP Error 400: Bad Request when requesting download of deciation

### ISSUE THREAD

**Issue by gonzens** [wix-incubator/DeviantArt-API#179]
Hi out there,
I use python lib to access the dA API. Wenn accessing deviations by **_download_deviation_** I get a 400 Error in some cases (with other deviations it works). I cannot see a reason, cause the deviations are in my favorits, and I collect the deviations by _**get_collection**_. When I log in on my account, I can access the deviations, and this is no mature content. 
In the description it is stated that download_deviation works "if allowed". What may be the reason for denie, when requested by API?

Thx, Gerhard/Gonz

**Comment by bjkim88** [comment]
Hello, Gonz,

Based on your explanations, I think it could be the case where the author disabled the download of the deviation from the submit option.
I suggest checking the error response. You probably got **error_description: "Deviation not downloadable."** and **error_code: 2**
You can also checking if the deviation will be downloadable by checking **is_downloadable** field of a deviation object.

I hope this helps.

Thank you.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
