### ISSUE TITLE
Include big avatar variants in API response

### ISSUE THREAD

**Issue by SeinopSys** [wix-incubator/DeviantArt-API#182]
The current [user object](https://www.deviantart.com/developers/http/v1/20200519/object/user) specifies a single `usericon` field which is currently set to the original 50x50 resolution avatar the site used to have before Eclipse, but now looking at a user's profile actually makes use of a larger avatar in the format `https://a.deviantart.net/avatars-big/e/x/example.ext?N` where `ext` is some arbitrary extension and `N` is probably the same as the cache busting parameter on the regular size ones.

These images are twice the resolution and would be much more suitable for displaying in my app than the current ones, but due to the highly dynamic nature of the URL components and without any sort of guarantee said components will be the same for both versions I'm not certain I can safely just add `-big` to the existing URLs and expect them all to function.

In case adding this image URL to the API response is not feasible I would either like to ask for some documentation updates regarding this or at least a confirmation here that both of these URLs should work interchangeably for the foreseeable future.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
