### ISSUE TITLE
Category Tree API No Longer Returns Data

### ISSUE THREAD

**Issue by rthaut** [wix-incubator/DeviantArt-API#183]
The [Category Tree API](https://www.deviantart.com/developers/http/v1/20200519/browse_categorytree/8e1e3d16e2d4a4cf1b2c65c5da3c3779) appears to be non-functional now.

All attempts to request a tree for any valid `catpath` (ex `/`, `/anthro`) yield the following response:
```json
{
    "error": "invalid_request",
    "error_description": "Category path not found.",
    "status": "error"
}
```

The documentation mentions the API is deprecated, but even specifying specific minor versions (as suggested) results in the same response.

**Comment by abdoulayeYATERA** [comment]
Same here.

**Comment by aaronpearce** [comment]
Per the documentation: `This endpoint is deprecated and will not return any results. It is scheduled for removal in the future versions.` As it is deprecated, minor versions will not affect this.
