### ISSUE TITLE
No RSS feed for tags?

### ISSUE THREAD

**Issue by Cyberwizzard** [wix-incubator/DeviantArt-API#184]
According to https://www.deviantart.com/developers/rss each search page should have an RSS link attached, which does not seem to be the case.

Also the page showing art by tag does not come with an RSS feed.

I tried manually crafting a https://backend.deviantart.com/rss.xml query but there seems no way of restricting it to tags.

So how do I tell the RSS API to fetch me results by tag?

**Comment by Cyberwizzard** [comment]
Any update on this?

**Comment by aaronpearce** [comment]
Hi, our documentation says most pages support RSS. Tags is not one of these supported pages.
