### ISSUE TITLE
How to get total watchers count?

### ISSUE THREAD

**Issue by emresakar** [wix-incubator/DeviantArt-API#185]
Hello,

It is possible to get total watchers count by using /user/watchers/{username} endpoint in a while(has_more) loop but it will create lots of requests. Instead of this, is it possible to get total watchers count in any other endpoints with just one or two requests?

Thanks,
Emre

**Comment by bjkim88** [comment]
Hello,

You can use /user/profile/{username} endpoint to get this information.
You need to pass "user.stats" as expand query, This will give you an extra user.stats object in your response.
The object will give you the number of watchers (people who watch you) and the number of friends (people you are watching)

I hope this solves your issue.
Thank you,

**Comment by ethanwangtang** [comment]
Is this no longer the case? Stats returns everything but the number of watchers.
