### ISSUE TITLE
Uploading files to stash

### ISSUE THREAD

**Issue by PixelVengeur** [wix-incubator/DeviantArt-API#186]
Hello,

I've been fighting with the DA&Sta.sh API for the past week or so, trying to get everything working together. I'm trying to build a script that would upload the content I make to multiple websites, and I can't figure out what parameter to use to upload to sta.sh. The goal is to have everything done through one script, and not require user interaction during the release of content.

So far the following works (after authorising through browser the application I made):
I request an access token through the `/oauth2/token` endpoint with grant_type set to `client_credentials`.
After discovering by myself and confirming the discovery with issue #32 that I can't use that token to call to the `/oauth2/stash/submit` endpoint, I call `/oauth2/token` once again, with a grant_type of `refresh_token`, my `client_id`, `client_secret` and the refresh_token I just got. I store the refresh token and access token I obtained in a file and move on.

After that, I can now call /oauth2/stash/submit to submit my file, and this is where I'm stuck. I can't find in the [doc](https://www.deviantart.com/developers/http/v1/20200519/stash_submit/0f1832daa6b58a05841ec6058520c4f3) what parameters I'm supposed to give to the query. So far I send my access token, to confirm that it is valid, and get in response

`"error":"invalid_request","error_description":"Please include content to submit.","error_code":400,"status":"error"`

which confirms that my access token is valid, but doesn't help figuring out what parameters to use. I saw Issue #134 but neither `filename` nor `name` seem to have any effect
I wrote everything in Python and use [Requests](https://pypi.org/project/requests/) to perform the calls.

Any help would be appreciated

**Comment by aaronpearce** [comment]
Hi,

Could you please share an example request? I presume you are submitting with multipart form data as the documentation specifies?

**Comment by PixelVengeur** [comment]
Holy, I found the solution, which was sitting under my nose the whole time, thank you @aaronpearce 


So I had glossed over the fact that I had to send the file as multipart/form data, but luckily for me Requests does that automatically **if a "files" argument is specified in the request**

What I used to have:
`url_stash = "https://www.deviantart.com/api/v1/oauth2/stash/submit"`
`files_stash = {"testFile": open("Path/to/file.png", 'rb')}`
`parameters_stash = {'access_token': myAccessToken, 'title': "titleOfTheDeviation", 'files': files_stash}`
`stashing = requests.post(url_stash, params=parameters_stash, headers=headers)`
`print("Stashing results: ", stashing.status_code, stashing.text)`

I had put `files` in the wrong place, it's supposed to go in the POST request itself, not in the parameters. The following is the correct way to proceed:

`url_stash = "https://www.deviantart.com/api/v1/oauth2/stash/submit"`
`files_stash = {"testFile": open("Path/to/file.png", 'rb')}`
`parameters_stash = {'access_token': myAccessToken, 'title': "titleOfTheDeviation"}`
`stashing = requests.post(url_stash, params=parameters_stash, headers=headers, files=files_stash)`
`print("Stashing results: ", stashing.status_code, stashing.text)`

Thank you again for indirectly bringing that to my attention :)

**Comment by PixelVengeur** [comment]
I'm reopening this instead of creating another issue, as it's still a problem related to submitting to sta.sh

So, after fixing nooks and crannies in my code and double checking the upload was going smoothly, I noticed something a bit unusual: when passing arrays as arguments to the API, it only seems to register the last element of the array, disregarding all the others, whatever size of array I use.

My code is the following:
`url_stash = "https://www.deviantart.com/api/v1/oauth2/stash/submit"`
`tags = ["Tag1", "Tag2", "Tag3"]`
`artist_comments = "Stuff that goes in the comment"`
`parameters_stash = {'access_token': access_token, 'tags': tags, 'title': "Title of the deviation", 'artist_comments': artist_comments}`
`files_stash = {"testFile": open(image, 'rb')}`
`stashing = requests.post(url_stash, params=parameters_stash, headers=headers, files=files_stash)`
`print("Stashing result: ", stashing.status_code)`

As I stated above, I write my code in Python, and I'm wondering if that has anything to do with my issue. Python does not have an "array" type, but rather multiple types of array: lists, dictionaries, tuples and sets. I tried all four, and even tried a [NumPy](https://numpy.org/doc/stable/reference/generated/numpy.array.html) array, to no avail, when uploading the file to sta.sh and subsequently publish it, it only gets tagged with the last tag in the array.

Any help or comment is appreciated :)

**Comment by PixelVengeur** [comment]
7 months later, I found the issue coming back to this project. I don't know the exact reason why, but when using `'tags'` in the request, which is not the right keyword, the API still fetches the first tag of the list.
The right keyword to use is not `'tags'` but `'tags[]'`. That's the whole issue. The rest works fine.

**Comment by houserwx** [comment]
Changing the name made the upload work, but did your tags show up??

**Comment by PixelVengeur** [comment]
@houserwx Yes, my tags do show up properly when using the code above

**Comment by houserwx** [comment]
OK, so for some reason to get a description I had to use deviation_description for the parameter
IE: {'deviation_description': 'A description'}  and that works, but is there anywhere in sta.sh I can see that the tags uploaded properly?  Because I tried the following:
{tags=["hash1","hash2","hash3","hash5","hash6","hash7"]}
and 
{tags[]=["hash1","hash2","hash3","hash5","hash6","hash7"]}
on the stash upload, to no effect.

I also tried using those same values on the publish from stash to deviantart call, as well as serialized_tags which is the data-item that appears on the submit page of stash.
If tags show up somewhere in stash, and you could assist, it would be much appreciated.  

PS: I am actually posting from .NET but it shouldn't matter since its still a multi-part form.....

**Comment by houserwx** [comment]
In case anyone happens on this, the required format for tag is the following:
"tags[0]=tagfirst&tags[1]=tagsecond&tags[2]=tagsthird" it does NOT accept an array like "tags[]=[tagfirst,tagsecond,tagthird]"
