### ISSUE TITLE
Using the limit parameter returns a random number around that parameters value

### ISSUE THREAD

**Issue by Reilaen** [wix-incubator/DeviantArt-API#187]
Hello everyone,

using `https://www.deviantart.com/api/v1/oauth2/browse/popular?q=otter&access_token=' . $accesToken . '&limit=20&offset=0&timerange=alltime`

Returns 19 results instead of the expected 20 for me. In the following pages results fluctuate around this limit. Is that normal behaviour?

**Comment by bjkim88** [comment]
Hello,
That would be an expected behaviour if you're using mature_content = false.
You might get less result than 20 deviations, but you can still rely on the next_offset value to parse deviations in the result without skipping results.

I hope this helps,
Thank you.
