### ISSUE TITLE
RSS feeds are broken

### ISSUE THREAD

**Issue by nnuudev** [wix-incubator/DeviantArt-API#189]
RSS feeds for galleries stopped working properly about 24 hours ago.

This was a previously working feed for [this folder](https://www.deviantart.com/andypriceart/gallery/36985463/my-little-pony-devious-folder), it doesn't work anymore:
https://backend.deviantart.com/rss.xml?type=deviation&q=gallery%3Aandypriceart%2F36985463
Notice how even though the title is still **DeviantArt: andypriceart/36985463's gallery**, the results are the most recent deviations from all users, instead of just the deviations in the specified folder.

General feeds for users are broken too. Here's the previously working feed for [the same user](https://www.deviantart.com/andypriceart/gallery), now it doesn't work either:
https://backend.deviantart.com/rss.xml?type=deviation&q=gallery%3Aandypriceart
Again, the title is **DeviantArt: andypriceart's gallery**, but the results don't include any submission from this user anymore.

Both kinds of feeds worked as expected yesterday, so the change that broke them had to be very recent.

**Comment by aaronpearce** [comment]
Closing this ticket due to its age. If this is still an issue, please feel free to reopen. Thanks!
