### ISSUE TITLE
Redirect URI not valid?

### ISSUE THREAD

**Issue by jason5122** [wix-incubator/DeviantArt-API#191]
Hi, so I've tried to use the Authorization Code grant type, using a `redirect_uri` of `http://localhost:8080`. Using https://github.com/dcarley/oauth2-cli as referenced in #188, and visiting the given URL, I get a response in the that says "The redirect_uri is not valid". Can anyone reproduce this? Does anyone have a method that's been working for them?

**Comment by aaronpearce** [comment]
Did you add this redirect_uri to your app on DeviantArt?

**Comment by jason5122** [comment]
I did, yes. Coming back to this with more knowledge, I now know that a local server is required for the typical OAuth2 flow. This is the only method DeviantArt supports, right?

I was hoping this wasn't necessary — I believe Google's flow can use the URI `urn:ietf:wg:oauth:2.0:oob`, which actually redirects it to the browser (see [here](https://developers.google.com/youtube/v3/live/guides/auth/installed-apps)). It's stated in that link that the URI should be used "if the client cannot listen on an HTTP port without significant modifications to the client."

**Comment by aaronpearce** [comment]
Correct, we do not support redirects to the browser.
