### ISSUE TITLE
How to oauth2/browse/popular with must include keyword

### ISSUE THREAD

**Issue by FurkanGozukara** [wix-incubator/DeviantArt-API#192]
I would like to search deviations with must include keyword

So are there such feature?

I am talking about oauth2/browse/popular : https://www.deviantart.com/developers/http/v1/20200519/browse_popular/73900c76a9806d17d78956830797d15d

so lets say i want to search for "mega charizard" and it should include these word

but not exactly it is about must include

like : **my great _mega charizard_ v2**

**Comment by aaronpearce** [comment]
A query such as this may do what you are requesting.

https://www.deviantart.com/developers/console/browse/browse_popular/73900c76a9806d17d78956830797d15d?category_path=&q=%22mega+charizard%22&timerange=&offset=&limit=&with_session=false&expand=&grant_type=authorization_code
