### ISSUE TITLE
RSS HTTP 403

### ISSUE THREAD

**Issue by frobinsonj** [wix-incubator/DeviantArt-API#194]
When periodically fetching the RSS feeds for a user's deviations, I sometimes get a 403.

What would be the possible cause of this and how can it be avoided?

Thanks in advance.

**Comment by aaronpearce** [comment]
Hi @frobinsonj,

How quickly are you accessing the RSS feeds? You may be hitting rate limits and need to slow down your fetching.

**Comment by JakeyPrime** [comment]
Shouldn't a rate limit properly return a 429 and not a 403? 

Regardless, I'm having the same issue. 

Seems to be like rolling the dice on either getting an error or getting a feed, checking them every 3 minutes, as I figured 1 or 2 minutes would be too much.

**Comment by aaronpearce** [comment]
It is quite common to utilise a 403 for rate limit errors as the service is forbidding your service request. I'll talk to some other team members to confirm this is the case in this example.

To avoid this, we suggest moving to the full API system which has this same data in a better format with authentication applied.

**Comment by aaronpearce** [comment]
Could either of you please share the full error or a screenshot of this so I can pass it along to the correct team member for more debugging?

**Comment by frobinsonj** [comment]
This appears to have been an issue with us expecting to receive a 429 response instead of the 403. I believe changes on our end have fixed the issue we were experiencing. Thanks for your response.
