### ISSUE TITLE
Add Notifications/Unread to Messages user endpoint

### ISSUE THREAD

**Issue by MightyPatamen** [wix-incubator/DeviantArt-API#197]
I really don't want to reverse engineer to simulate user interactions to get notifications
That's really important to some of the people I encountered IRL, pretty many of my friend would like to get notifications on some kind of Telegram/What'sApp/etc messengers about activity on their accounts

I see there were feed/notifications but it's deprecated

**Comment by aaronpearce** [comment]
Hi,

`messages/*` is the group of endpoints to look into for this feature at this current time.

Thanks!

**Comment by MightyPatamen** [comment]
> Hi,
> 
> `messages/*` is the group of endpoints to look into for this feature at this current time.
> 
> Thanks!

How to check unread notifications then?

[https://www.deviantart.com/_napi/shared_api/unread] is not an option cause I can access it only using reverse engineering user interactions

I really don't understand what in the Messages/Feed or Messages/Feedback endpoints could provide the unread status of the notification

Please could you provide a little example?
