### ISSUE TITLE
Is there a /deviation/create endpoint somewhere?

### ISSUE THREAD

**Issue by ratioratiocode** [wix-incubator/DeviantArt-API#198]
I'm reading this doc article: https://www.deviantart.com/developers/http/v1/20210526
there are endpoints to create journals and literatures, but I can't find one to create a standard deviation.
I also read this issue ticket: https://github.com/wix-incubator/DeviantArt-API/issues/188
and by reading your answers it seems like there's a way to post and publish through endpoints.

Could you tell me what's the endpoint I should use in order to post and publish a standard deviation?

**Comment by aaronpearce** [comment]
You'd be looking to use `stash/submit` to upload to Sta.sh then utilising `stash/publish` to publish a standard deviation.

Hope that helps!
