### ISSUE TITLE
/user/statuses/{statusid} says "statusid is not a valid UUID"

### ISSUE THREAD

**Issue by ratioratiocode** [wix-incubator/DeviantArt-API#199]
It looks like it doesn't matter what UUID I send, it always says that's not a valid one.
I use the console to post a status and retrieve its statusid (https://www.deviantart.com/developers/console/user/user_statuses_post/a467847281672ece48b364d55d8b3400)
Then I use the console to retrieve a status object by sending the statusid I previously received (https://www.deviantart.com/developers/console/user/user_statuses_status/016bc873626ba9c32017235fc5fdab91)

How am I supposed to write down the statusid to let the server recognize it?

**Comment by aaronpearce** [comment]
Hi,

The `user/statuses/{statusid}` is used to retrieve an older style of status posts that are no longer created. I'll make a note with our team to update this portion of the documentation appropriately. 

The `user/statuses/post` endpoint does create new style statuses which are deviation objects.  So you should be using `deviation/{deviationid}` to retrieve a status. 

Sorry for the inconvenience of the documentation in this case.
