### ISSUE TITLE
Get client code in a single request

### ISSUE THREAD

**Issue by Wizer21** [wix-incubator/DeviantArt-API#201]
Hello,
I'm trying to fetch client's code a single request.

1// Get Code
`https://www.deviantart.com/oauth2/authorize?response_type=code&client_id=myid&redirect_uri=https://deviantgallery.netlify.app/&state=1234`

2// Authorize application
`https://www.deviantart.com/oauth2/authorize?response_type=token&client_id=muid&redirect_uri=https://deviantgallery.netlify.app/&state=1234`

The request 1 allow me to get the code, but only if the user already authorized the application.
Else I get the following error
`error=invalid_request&error_description=The+response_type+MUST+be+token`

So I'm trying to figure out if there is a way to merge the both requests.

Thanks !

**Comment by aaronpearce** [comment]
Hi,

Please refer to the documentation [here](https://www.deviantart.com/developers/authentication) under "Using The Client Credentials Grant".

As you can see, the documentation there says to utilise the `https://www.deviantart.com/oauth2/token` endpoint with differing data to what you have above.

If you want to authorise a singular user and receive a user specific access token you need to call `oauth2/authorize` then `oauth2/token`

**Comment by Wizer21** [comment]
I'm trying to get a refresh_token

So I need to do it in 3 requests and send the user two time on DeviantArt ?

1 - Send the user on DeviantArt to be sure he authorized the application
`https://www.deviantart.com/oauth2/authorize?response_type=token...`

2 - Send the user on DeviantArt to get the `code`
`https://www.deviantart.com/oauth2/authorize?response_type=code...`

3 - Request the `refresh_token`
`https://www.deviantart.com/oauth2/token?grant_type=authorization_code&code=123456...`

Thanks for the extremely fast response !

**Comment by aaronpearce** [comment]
Follow the guide for "Using The Authorization Code Grant". This is the correct flow for getting a user token. You do not want to call with `response_type` of `token` for this use case.

**Comment by Wizer21** [comment]
Yes, but if I skip the `response_type=token` request, I get an error.

For example, this
`https://www.deviantart.com/oauth2/authorize?response_type=code&client_id=19638&redirect_uri=https://deviantgallery.netlify.app/&state=1234`

Give me the following response
`https://deviantgallery.netlify.app/?error=invalid_request&error_description=The+response_type+MUST+be+token.&state=1234`

**Comment by aaronpearce** [comment]
You have made your app on DeviantArt as a `implicit` grant app. Please refer to the documentation for that grant, or edit your app to make it utilise the authorisation code grant.

**Comment by Wizer21** [comment]
Oh, yes you right.

It fixed the issue, thanks you so mush for your help !
