### ISSUE TITLE
403 Error || The request could not be satisfied

### ISSUE THREAD

**Issue by JeRabix** [wix-incubator/DeviantArt-API#203]
I'm making a request for 
https://www.deviantart.com/api/v1/oauth2/gallery/folders/copy_deviations
I pass the headers as it is specified in the documentation
Accept-Encoding - gzip, deflate, br
User-Agent - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

If I don't pass parameters, I get a 400 Bad request error
with validation errors.
But if I add at least 1 key to Form Data or json
, I immediately start getting an error
in HTML format 
CODE: 403
ERROR: The request could not be satisfied

**Comment by aaronpearce** [comment]
This API does not support multipart form-data or JSON, this is why you get an error.

**Comment by JeRabix** [comment]
> This API does not support multipart form-data or JSON, this is why you get an error.

With x-www-form-urlencode i has the same mistake

**Comment by aaronpearce** [comment]
Reading the documentation, this is a GET request, so all parameters should be in the URL. https://www.deviantart.com/developers/console/gallery/gallery_folders_copy_deviations/b635c560c3412cc591a95eec53fb30da

**Comment by JeRabix** [comment]
> 

![image](https://user-images.githubusercontent.com/46298617/177648209-f68ada13-6a47-4fbc-a654-e0461115aa9d.png)
POST!

**Comment by aaronpearce** [comment]
See the main URL above saying it is a GET request. 

I will mention to our team that the parameter section is incorrect.

**Comment by JeRabix** [comment]
GET parameters they don't work either

> See the main URL above saying it is a GET request.
> 
> I will mention to our team that the parameter section is incorrect.

**Comment by JeRabix** [comment]
![image](https://user-images.githubusercontent.com/46298617/177648432-be6ae01e-bca2-413a-b71d-e87de721009a.png)

**Comment by aaronpearce** [comment]
Thanks for that. We're looking into it on our side now.

**Comment by aaronpearce** [comment]
To help you out in the mean time, the team has shared that it is a POST request.

Ensure you are sending the parameters in the body of the POST request, not as query parameters 

You can test our API using the console here: https://www.deviantart.com/developers/console/gallery/gallery_folders_copy_deviations/b635c560c3412cc591a95eec53fb30da. Ignore the GET in request in this case.

**Comment by JeRabix** [comment]
> To help you out in the mean time, the team has shared that it is a POST request.
> 
> Ensure you are sending the parameters in the body of the POST request, not as query parameters
> 
> You can test our API using the console here: https://www.deviantart.com/developers/console/gallery/gallery_folders_copy_deviations/b635c560c3412cc591a95eec53fb30da. Ignore the GET in request in this case.

My problem remains the original one until I pass the request parameters - I get a validation error.
As soon as I start passing at least some parameter, it doesn't matter from this API request or not
, I can just add test => 1
immediately I start getting an error
403 The request could not be satisfied from Cloud Front

**Comment by JeRabix** [comment]
I would be very grateful if you would provide me with an example in a program like postman or its equivalent request so that I can get an example that I can copy. The console does not help - because it does not show the full request that it sends to the API itself, it sends a request to one back, and that in turn already forms the request itself, which I cannot see

**Comment by JeRabix** [comment]
Oops, sorry I forgot to change GET to POST, now everything works.
Thank you for your prompt help!
