### ISSUE TITLE
Contribute to folder API route

### ISSUE THREAD

**Issue by JeRabix** [wix-incubator/DeviantArt-API#204]
Can you please tell me if there is an endpoint API for publishing your devian to a group?
![image](https://user-images.githubusercontent.com/46298617/177708548-e6fe6081-9cff-40ff-9852-10bf2b90321b.png)

I thought that gallery/folders/copy_deviations works like this, but it just responds success: true and nothing happens, copying is possible only inside its gallery.

**Comment by JeRabix** [comment]
I use
https://www.deviantart.com/api/v1/oauth2/deviation/edit/{deviationid}
This works for my galleries, but as with gallery/folders/copy_deviations it ONLY works for my galleries

**Comment by aaronpearce** [comment]
Hi, none of the APIs at this stage support moving items to groups.

Movement and editing is within your own gallery only.

**Comment by JeRabix** [comment]
Can I participate in the development?

**Comment by JeRabix** [comment]
@aaronpearce such an opportunity has not been realized?  Is it possible to clarify whether this is planned in the near future?

**Comment by aaronpearce** [comment]
@JeRabix I no longer work for DeviantArt so am unable to help you with this.
