### ISSUE TITLE
popular api search term ignore ?

### ISSUE THREAD

**Issue by abdoulayeYATERA** [wix-incubator/DeviantArt-API#206]
The search term on the popular api is ignored.
Whatever the value of the parameter q, the response is the same

For example the following two requests give back the same result:

~~~
https://www.deviantart.com/api/v1/oauth2/browse/popular?q=sonic
https://www.deviantart.com/api/v1/oauth2/browse/popular?q=space
~~~

I'm able to reproduce the error on the DA console (https://www.deviantart.com/developers/console/browse/browse_popular/73900c76a9806d17d78956830797d15d)

Thanks!

**Comment by Voldrix** [comment]
I'm seeing the same issue. Any query string to /popular is returning the same generic results. The query search for /newest seems to work okay.
