### ISSUE TITLE
Feature Request: Advanced Search

### ISSUE THREAD

**Issue by Voldrix** [wix-incubator/DeviantArt-API#207]
I would like the search APIs to be able to:

tags: search multiple tags (AND logic)
tags: ignore underscores and plurals (so a search for #foobar would include #foo_bars and vice versa)
tags: negative search (omit this -#tag) [as it works for regular search]
recommended / newest / popular: combine text and tag queries (with AND or OR logic)
all: filter results by user metrics such as subscribers, views, gallery count, etc
all: a singular option to omit all AI generated images

I think this would give more inclusive results for very specific queries, as well as make it easier to discover lesser-known artists. I certainly find myself wanting these capabilities when trying to find specific things.

I don't know how you associate related/recommended images, if you apply your own meta tags on the backend, but having some insight into that system would be really interesting and useful.

Thank you for your efforts. I realize that is a lot, but these features would greatly improve content navigation.

**Comment by muteor** [comment]
Maybe one day we are not currently developing new features for the API.

**Comment by DineshSolanki** [comment]
@muteor at least don't remove existing ones without an alternative, many browse endpoints are removed now, can you please tell me the recommended way to search now
