### ISSUE TITLE
No way to require Client Credentials when registering app

### ISSUE THREAD

**Issue by Nemris** [wix-incubator/DeviantArt-API#211]
Good day.

Based on what I read at https://www.deviantart.com/developers/authentication, I should be able to require Client Credentials when registering an application, yet only the Authorization Code and Implicit grant types can be selected from the dropdown.

Additionally and just to confirm - my use case is simply to fetch and analyze publicly-available comments, thus I shouldn't need to have my program act on behalf of a user. Is this correct?

If more information is needed, I'll be happy to provide it.

**Comment by muteor** [comment]
Client creds are always available, you don't need to specify when creating the app.
