### ISSUE TITLE
Can't register an app which is a Chrome extension

### ISSUE THREAD

**Issue by panyann** [wix-incubator/DeviantArt-API#212]
Hello,
I wanted to register the plugin I make for chromium browsers.
I wanted to use implicit way for javascript, but the problem is - I also need to provide redirect URL to my app.
The extension's URL is dynamic, it will be different for all users, so I can't give you any redirect URL.
It also doesn't have the HTTPS, since it's just chrome extension.

It looks like this and part of it is changing (you can guess which one):
chrome-extension://akcpjnemfjinmeghjkoeheddnjbngaio/index.html

Does it mean that the deviantART API can't be used for browser plugins or you can fix it somehow?

**Comment by muteor** [comment]
I am sure there must be a way to do OAuth2 with extensions but I have not done it myself.

**Comment by panyann** [comment]
Thanks for nothing then.
