### ISSUE TITLE
DeviantArt rss feeds disabled depending on server? 

### ISSUE THREAD

**Issue by Destroyer77d** [wix-incubator/DeviantArt-API#213]
Hi, I've been using BazQux rss reader to view the deviations on dA from people and they all of a sudden stopped. According to the person that manages the reader the German and US servers were blocked from receiving the rss feed data.

He told me that: "They could use: dig [bots.bazqux.com](http://bots.bazqux.com/) to find all the IPs reader can make requests from."

If it's possible I'd love to be able to see this unblocked. Or at least an explanation as to why it's happening. Thanks

**Comment by chrisbolt** [comment]
Apologies, some of our rules to block traffic due to DOS attacks needed to be adjusted. Please let us know if things are fixed now, thanks!

**Comment by Destroyer77d** [comment]
> Apologies, some of our rules to block traffic due to DOS attacks needed to be adjusted. Please let us know if things are fixed now, thanks!

That seems to have fixed it! Thanks so much! I appreciate everything you guys manage in the background
