### ISSUE TITLE
i can't use the update deviation order endpoint

### ISSUE THREAD

**Issue by BanceSt** [wix-incubator/DeviantArt-API#214]
Hi !
i can't use this request because it's block by CORS policy but i don't know why, i can use other endpoint without problem such as /collections/all or /collections/{folderid}. I use the Authorization Code, and a scope = "browse collection".

So i don't know why i can't use it

**Comment by sasha-lerner** [comment]
Hello, you need to use "stash" and "publish" scopes for this endpoint.
For the future, always check scopes list under authentication section in endpoint doc

**Comment by BanceSt** [comment]
> Hello, you need to use "stash" and "publish" scopes for this endpoint. For the future, always check scopes list under authentication section in endpoint doc

i want to reach the /collections/folders/update_deviation_order, "stash" and "publish"   is not listed as required
![image](https://github.com/wix-incubator/DeviantArt-API/assets/59577061/12041dbe-5bc7-4ed3-8a6a-d3c9885e8a36)
And i already get in the past a scope error, and it says what scope i need when that happen, in this case i'm block by the CORS

**Comment by sasha-lerner** [comment]
are you doing the POST request? this endpoint does not support GET like the others you mentioned

**Comment by BanceSt** [comment]
yes i use a POST request
![image](https://github.com/wix-incubator/DeviantArt-API/assets/59577061/84bfe464-a153-4307-b84e-849555fab4dd)

**Comment by sasha-lerner** [comment]
It appears the issue is on your side. our endpoint should not be setting Access-Control-Allow-Origin header
your next step would be to debug the request / response raw data so you can see what the error is. axios client is likely masking the issue

**Comment by BanceSt** [comment]
yes i can't see the exact erreur it just says "network error" - "axios error". Does there is a way through axios or other means to get a precise debug ?

**Comment by BanceSt** [comment]
i fix it, i put all the params in the url. sorry i'm new in that I thought that if is a POST method you have to pass the param through data in json only
