### ISSUE TITLE
/stash/publish galleryids parameter

### ISSUE THREAD

**Issue by Derewen** [wix-incubator/DeviantArt-API#220]
using galleryids parameter does not work, using gallery UUID (called "folderid") fetched from /gallery/folders does nothing and image gets published to Featured gallery (fallback?)

I was able to recreate this with console (under https://www.deviantart.com/developers/console/stash/stash_publish/a799a5c0967dca14e854286df9746793) using the same UUID

documentation doesnt show example usage of galleryids https://www.deviantart.com/developers/http/v1/20210526/stash_publish/a799a5c0967dca14e854286df9746793
so I am not 100% sure that is the correct UUID (tho I havent found any other way to fetch and also the folderid seems tied to the name of the gallery, so I suppose thats the correct usage?)

**Comment by ctlemonzest** [comment]
Bruh this is doing my head in i'm trying the same thing, the api documentation has conflicting information, one part says you need the gallery id the other part says you need the category path but neither work lol

**Comment by ctlemonzest** [comment]
I think the api is a lost cause for now my browser bot/macro program runs better than my integrated api program lmfao

**Comment by Derewen** [comment]
> Bruh this is doing my head in i'm trying the same thing, the api documentation has conflicting information, one part says you need the gallery id the other part says you need the category path but neither work lol

not sure but I think catpath is on deprecated endpoint

I hope someone can look at this, I tried to contact support and was redirected here

**Comment by antipiks** [comment]
I know how to get the uuid for a new gallery, and indeed with it the publishing happens correctly, but maybe someone knows how to find the uuid for already existing albums?

**Comment by sasha-lerner** [comment]
https://www.deviantart.com/developers/http/v1/20240701/user_profile/0b06f6d6c8aa25b33b52f836e53f4f65 lists gallery uuids
