### ISSUE TITLE
/download/{deviationid} won't get some results

### ISSUE THREAD

**Issue by marcnetts** [wix-incubator/DeviantArt-API#221]
Example with deviation 13A14937-CC91-A649-1B51-5D1CF435307C, works in sandbox but as a request says the deviation is not downloadable. Guess it's tied to it being mature, but mature_content=true had the same result
![image](https://github.com/wix-incubator/DeviantArt-API/assets/62448302/d7c7a511-1481-4ca2-a79e-cffdffe005da)
![image](https://github.com/wix-incubator/DeviantArt-API/assets/62448302/ad58b315-24f9-4c71-b548-e084c8ab7f41)

**Comment by muteor** [comment]
This is likely an authentication difference between console and your other request.

**Comment by marcnetts** [comment]
Care to provide more details? I'm using a valid Bearer token, if otherwise I'd get a 401 response. Other calls do work.

**Comment by muteor** [comment]
Different user maybe? The error usually means the download is private and the user is not the owner.

**Comment by marcnetts** [comment]
The download is not private. Did you check the deviation?
https://www.deviantart.com/soumakyo/art/Ulala-Space-Dressing-Game-22583264

**Comment by muteor** [comment]
Which user are you using to call the endpoint?

**Comment by marcnetts** [comment]
ptcghunter for both console and other request

**Comment by muteor** [comment]
This is working for me:

`curl --verbose 'https://www.deviantart.com/api/v1/oauth2/deviation/download/13A14937-CC91-A649-1B51-5D1CF435307C' -d access_token=`

```< HTTP/2 200
< content-type: application/json; charset=utf-8
< content-length: 747
< date: Wed, 04 Oct 2023 05:58:51 GMT
< server: Apache
< cache-control: Private, no-cache, no-store, must-revalidate, max-age=0, max-stale=0, post-check=0, pre-check=0
< pragma: no-cache
< expires: 0
< vary: Accept-Encoding
< x-backend: web_http_back
< x-cache: Miss from cloudfront
< via: 1.1 1557bb1095d8a4a6e7c25ddbf3b48cec.cloudfront.net (CloudFront)
< x-amz-cf-pop: LHR50-P2
< x-amz-cf-id: VtLz75XeWV7ZF43lSeaqPDlHS54SkyEntBCC3TlQOoU0sJwcjMYjHw==
<
* Connection #0 to host www.deviantart.com left intact
{"src":"https:\/\/wixmp-ed30a86b8c4ca887773594c2.wixmp.com\/f\/9bed27a4-1a3d-435d-9611-1e64c8896161\/ddg1cw-4eb39f76-fc21-4dff-bd56-9cb177068c08.swf?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImV4cCI6MTY5NjM5OTczMSwiaWF0IjoxNjk2Mzk5MTIxLCJqdGkiOiI2NTFjZmYxYmU4YzU3Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvOWJlZDI3YTQtMWEzZC00MzVkLTk2MTEtMWU2NGM4ODk2MTYxXC9kZGcxY3ctNGViMzlmNzYtZmMyMS00ZGZmLWJkNTYtOWNiMTc3MDY4YzA4LnN3ZiJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTpmaWxlLmRvd25sb2FkIl19.tl9v1ontLL0nH6AAwg0TuyPmFSu1O0BvW6XiBK6vkec","filename":"ulala_space_dressing_game_by_soumakyo_ddg1cw.swf","width":800,"height":700,"filesize":650519}
```

Also checked your user and everything looks correct, the user is over 18 and allowed to download the file etc. One thing to check is that you are not using client credentials auth because that defaults to under 18.

**Comment by marcnetts** [comment]
Tried your request in curl, oddly same result as before 🤔
`curl --verbose 'https://www.deviantart.com/api/v1/oauth2/deviation/download/13A14937-CC91-A649-1B51-5D1CF435307C' -d access_token=(mytoken)`
```
[...]
< HTTP/2 400
< content-type: application/json; charset=utf-8
< content-length: 109
< date: Thu, 05 Oct 2023 00:40:52 GMT
< server: Apache
< cache-control: Private, no-cache, no-store, must-revalidate, max-age=0, max-stale=0, post-check=0, pre-check=0
< pragma: no-cache
< expires: 0
< vary: Accept-Encoding
< x-backend: web_http_back
< x-cache: Error from cloudfront
< via: 1.1 827f449bafa54811021e4ae2cea19228.cloudfront.net (CloudFront)
< x-amz-cf-pop: GRU3-P5
< x-amz-cf-id: Qf0QlGfZdZbdkeX10CFbFfSMYHRXnW071mMCNS0Aq1Jm4s8s7QuJMg==
<
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Connection #0 to host www.deviantart.com left intact
{"error":"invalid_request","error_description":"Deviation not downloadable.","error_code":2,"status":"error"}
```

**Comment by marcnetts** [comment]
Upon inspection, that token was indeed a client credential and not an auth code; though I expected another kind of error, makes sense now. Thanks 👍
