### ISSUE TITLE
dA rss feeds blocked again?

### ISSUE THREAD

**Issue by Destroyer77d** [wix-incubator/DeviantArt-API#222]
Hi again, I was noticing absolutely zero updates or extremely few updates leading to none for my dA feeds through RSS. I suspect it's similar to the last time so I'll post the content of the last ticket here for reference: 

Hi, I've been using BazQux rss reader to view the deviations on dA from people and they all of a sudden stopped working. According to the person that manages the reader the German and US servers were blocked from receiving the rss feed data.

The owner of BazQux Reader has requested that I add: you can use [bots.bazqux.com](http://bots.bazqux.com/) to whitelist by a list of IPs, and/or add User-Agent containing BazQux to their whitelist.

to prevent this from happening again.

Thanks for the help

**Comment by chrisbolt** [comment]
Hi, we've made some changes, can you check if this is fixed now? Thanks!

**Comment by Destroyer77d** [comment]
Yup, it seems to be working. Thanks very much!

So...is BazQux a service that can be whitelisted for you guys? I mentioned it last time I believe and it seems odd that Inoreader wasn't having any issues showing the same dA feeds. I was also wondering if there was a way to more directly reach you guys since nobody seems assigned to most of these issues listed on here.

**Comment by chrisbolt** [comment]
Unfortunately we can't whitelist individual services.

Inoreader was probably not affected due to polling less frequently, or due to backing off after errors.

In the future I would recommend contacting DA support at deviantartsupport.com (and mention this issue for context) and it will be sent to the right people. Thanks!

**Comment by Destroyer77d** [comment]
Just to add, and I feel bad for I don't know if this re-opens the ticket. I started this out by contacting deviantart support to let them know about this issue and they immediately sent a link to this github site to ask you guys about it.

I've passed on the other details to the BazQux community forum. Very helpful details. Thanks again.

**Comment by chrisbolt** [comment]
Don't feel bad, it didn't reopen the issue, and in this case DeviantArt support also brought your comment to the attention of the right people, so it all worked out 🎉
