### ISSUE TITLE
can't access some images in very large (>10k) galleries

### ISSUE THREAD

**Issue by colin-heberling** [wix-incubator/DeviantArt-API#224]
When I make API requests to download from very large galleries (such as this one: https://www.deviantart.com/icedragon4u/gallery/all) the API doesn't return any more download links after ~9.5k-10k most recent image uploads to the gallery.  If an artist organizes images into different folders, that can mitigate the issue, but often times they may have many images that are not organized into any folders, and are only accessible through the entire gallery.  In this case, with the current API bug, it may make many or even the majority of an artist's gallery inaccessible through the API.  The particular artist I have linked has also told me that they have already reached their folder limit, so asking them to put everything in folders is not an option, unless the folder limit is extended.  Unless this was somehow intentional, this seems like a bug.

Could you look into fixing this?

**Comment by sasha-lerner** [comment]
this is an intentional limit

**Comment by colin-heberling** [comment]
Why?  With AI art galleries, this threshold will be increasingly surpassed more and more often.  That limit doesn't make any sense.

**Comment by sasha-lerner** [comment]
you can use endpoint '/gallery/{folderid}' as a workaround

**Comment by colin-heberling** [comment]
Did you read my opening message?  I've already tried that as a workaround, and it doesn't always work, because the artist may have images that are not organized in folders, and there also appears to be a limit on how many folders an artist can put on their profile, so that's not a suitable solution.

You still didn't answer my question: why is there an intentional limit on how many images that can be downloaded from a single gallery to begin with?  What is the purpose of that?  There's already quite a bit of rate limiting, and downloading from multiple artists can easily download significantly more images than the limit imposed for a single artist, so if you say the reason is for individual user bandwidth limiting, then that reason doesn't fly.

As far as I can tell, it's an arbitrary, outdated limit, that should be updated, unless you can tell me otherwise.  If you know that it's an intentional limit, then seemingly it should be very easy to update.
