### ISSUE TITLE
Cannot publish via neither UI nor API

### ISSUE THREAD

**Issue by tuttle** [wix-incubator/DeviantArt-API#225]
Hi, I have a free account and I try to submit my first deviation.

Using UI: I upload to Stash without problems, click **Submit Now** button in DA, green Successful popup on the bottom right corner, then I'm immediately redirected to the 404 Oops page with URL 'https://www.deviantart.com/deviation/<number>'.

So I tried via API, auth OK, simple entrypoints OK. Then I tried to publish the stashed image via `/stash/publish` endpoint. It returns **success** and I get the deviation UUID.

But even after several hours, the deviation does not appear in **All** gallery.

I expect I don't need to use `galleryids` in the `/stash/publish` call for the deviation to appear in All. If I need to fill it, what value it should be for **All**?

What am I doing wrong? And how do people submit any art via UI without 404? 
Thanks!

**Comment by muteor** [comment]
what username are you posting from?

**Comment by tuttle** [comment]
fixed, thanks
