### ISSUE TITLE
Does your API support submitting pics to DeviantArt?

### ISSUE THREAD

**Issue by pickhardt** [wix-incubator/DeviantArt-API#226]
Your support directed me to ask through this website.

Does your API support submitting pics to DeviantArt? I cannot figure out which API call to use. It looks like it only supports it for Stash but not the main DeviantArt website?

Thanks.

**Comment by muteor** [comment]
It does, you upload to stash and then publish to da from stash.

https://www.deviantart.com/developers/http/v1/20210526/stash_publish/a799a5c0967dca14e854286df9746793
