### ISSUE TITLE
Offset limit on Sta.sh /user/watchers/{username}

### ISSUE THREAD

**Issue by Olivery0307** [wix-incubator/DeviantArt-API#227]
I am working on a project and I am trying to fetch all the watchers of one user. I am wondering if there is a way to ignore the limit fetch the full lists of watchers?

**Comment by muteor** [comment]
No only way is to fetch in batches.

**Comment by Olivery0307** [comment]
What is the specific way to fetch it in batches?

**Comment by muteor** [comment]
The endpoint returns `has_more (boolean)` and `next_offset (integer|null)` you can use those to fetch a page at a time.

Docs: https://www.deviantart.com/developers/pagination

**Comment by Olivery0307** [comment]
has_more and next_offset return normally most of the time, but it will return "exceed the limit" whenever the watchers are more than  50,000. Is there a way to exceed this limit? I cannot find docs to solve that. Thank you!

**Comment by sasha-lerner** [comment]
what is the reason you want to fetch more than 50K watchers?
