### ISSUE TITLE
RSS doesn't work properly! 

### ISSUE THREAD

**Issue by AniAve** [wix-incubator/DeviantArt-API#228]
Hello! I'd like to ask you to help me generate proper RSS link for digital deviations for "Cyberpunk" query and sort it by popularity this month. I was trying https://backend.deviantart.com/rss.xml?type=deviation&amp;q=by%3Aspyed+sort%3This-week+meta%3Aall but it sorts by newest. Also I tried "https://backend.deviantart.com/rss.xml?type=deviation&q=cyberpunk&order=24" but it doesn't work properly: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbackend.deviantart.com%2Frss.xml%3Ftype%3Ddeviation%26q%3Dcyberpunk%26order%3D24

**Comment by sasha-lerner** [comment]
popular sorting is no longer supported
