### ISSUE TITLE
The way to fetch the data in batches for Sta.sh/user/watchers/{username}}?

### ISSUE THREAD

**Issue by Olivery0307** [wix-incubator/DeviantArt-API#229]
Is there a specific way/an instruction to fetch the data in batches in Python? We tried request but it only works for watchers less than 50,000. Thanks!

_Originally posted by @Olivery0307 in https://github.com/wix-incubator/DeviantArt-API/issues/227#issuecomment-1917139654_

**Comment by Olivery0307** [comment]
I am reaching out regarding my ongoing project that has hit the current API limit of 50,000 watchers per artist. The project is an academic project regarding my network science project.

I respect the platform's privacy standards and assure you that all data will be handled in strict compliance with your terms and privacy policy. I seek guidance on how to appropriately extend my access while upholding these standards. Since this is a network science project, the watcher and friend are the only two variables I will use. There are no images I will use for AI purposes. 

If possible, could we discuss potential pathways for accessing the additional data required for my project's success?

Thank you for considering my request. I am keen to proceed in a way that is mutually beneficial and respectful of DeviantArt's policies and community.

**Comment by sasha-lerner** [comment]
the limit is intentional and will not be changing
