### ISSUE TITLE
API Connection Issue

### ISSUE THREAD

**Issue by SomewhatDamaged** [wix-incubator/DeviantArt-API#232]
My unfurler was working just fine, then started getting 403 errors.

Contacted support, they told me to come here.

> I keep getting a 403 error from my Unfurler service trying to get data from your site.
> 
> In your API page, it says I should only get this error when I am not sending a user agent and/or have compression turned off: https://www.deviantart.com/developers/errors (I have ensured both are definitely not the case).
> 
> But, for 2 days now, I have not been able to log in (getting a 403 HTML page saying the request was blocked).
> 
> If this is a rate limit issue, is there a premium account type that gives higher rates?

This is the result from https://www.deviantart.com/oauth2/token and requesting a Client Credential (something my software was doing just fine before).

```HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: FTGrxXaIaFb4tIUXn1NHpW2nDiazzjZCCbMqEdyYXLWiu95pvgJakg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by AW0005** [comment]
Also experiencing this trying to do OAuth

**Comment by SomewhatDamaged** [comment]
> Also experiencing this trying to do OAuth

Let me take a guess, you're hosted on Digital Ocean?

**Comment by AW0005** [comment]
@SomewhatDamaged  I am, but I've been told there's at least one dreamhost hosted site experiencing it as well. (I use the oauth as a part of an open source site framework that's used by a number of people).

**Comment by SomewhatDamaged** [comment]
I've tried cycling through a few reserved IPs, but they all seem to be blocked.

Do DA really block entire Class C networks at a time?

**Comment by SomewhatDamaged** [comment]
Aaand I have started getting regular responses again. I guess either someone saw this and reset it or they have a days-long timeout on blocks.

**Comment by SomewhatDamaged** [comment]
And dead again. I'm done. Routing all my DA requests through TOR now, and cycling exit nodes every 10 requests. This is madness.

**Comment by SomewhatDamaged** [comment]
@AW0005 This is me from the future! I have a solution, in case you still need it.

Cloudflare Warp is a VPN that can be run on Linux and turned into a proxy. In the last year or so, I have experienced no 403s from DeviantArt.
