### ISSUE TITLE
Worst API of all time?

### ISSUE THREAD

**Issue by RobertJBlanch** [wix-incubator/DeviantArt-API#241]

**Comment by KarsonOdette** [comment]
Calm down.

**Comment by Yay295** [comment]
> to register an application to use the fucking thing you have to publish it to your deviantart page

You don't, actually. Instead of clicking "Save", click "Cancel". A client ID and secret will still be created and can be used; you just can't change anything else about your "app".

**Comment by RobertJBlanch** [comment]
> > to register an application to use the fucking thing you have to publish it to your deviantart page
> 
> You don't, actually. Instead of clicking "Save", click "Cancel". A client ID and secret will still be created and can be used; you just can't change anything else about your "app".

What a well designed system!

**Comment by SomewhatDamaged** [comment]
And now they're deleting random endpoints with no reason given: https://github.com/wix-incubator/DeviantArt-API/issues/244
