### ISSUE TITLE
Fetching deviations by time range

### ISSUE THREAD

**Issue by jojo080889** [wix-incubator/DeviantArt-API#243]
Hello! I'm working on a data science research project and I'm hoping to be able to query for deviations by a time period (specifically, deviations from 2021 to 2023). I couldn't find anything in the API documentation that seems like it would allow me to do this -- is there a way? 

(This data would not be for an app or other commercial purposes, and I would not need image data.)

Thank you!

**Comment by KarsonOdette** [comment]
Just a warning about your goal of data science: the API is rate limited, so
keep that in mind.

**Comment by sasha-lerner** [comment]
This functionality is not available on Deviant Art
