### ISSUE TITLE
How to replace https://www.deviantart.com/api/v1/oauth2/browse/deviantsyouwatch

### ISSUE THREAD

**Issue by c-chell** [wix-incubator/DeviantArt-API#244]
Hi, I just see DeviantArt decide to remove this API.
Now I have just a question, previoulsy I use the RSS feeds, but after some days I was blocked and need to cut and restart progressively the requests.
To solve this problem, I start to use the API of DeviantArt provide to check all new content from watched galleries :
https://www.deviantart.com/api/v1/oauth2/browse/deviantsyouwatch?access_token=*****&mature_content=true&limit=20&offset=0

But since a week (2024-07-29 11:16 UTC last working request), I receive a 404 with this content :
{"error":"invalid_request","error_description":"Api endpoint not found.","status":"error"}

How to replace this API or get an equivalent to avoid making 120 requests per hours and get blocked regularly ?

Best regards,
C_Chell.

**Comment by SomewhatDamaged** [comment]
Same. This is a big issue and I am trying to find an API way around it—and failing. Was this a mistake? Are you telling us we should scrape the `https://www.deviantart.com/notifications/watch/deviations` page?

**Comment by SomewhatDamaged** [comment]
Hrmm, one work-around would definitely be to use the `/gallery/all` endpoint, hitting it for every deviant the user is subscribed to. 

NGL, that's going to be a LOT of hits (currently tracking 100+ deviants).

**Comment by sasha-lerner** [comment]
The issue with browse/deviantsyouwatch endpoint is fixed
thanks for the report
