### ISSUE TITLE
How to pass a Hyperlink in the Image Description using api?

### ISSUE THREAD

**Issue by Neolegen** [wix-incubator/DeviantArt-API#249]
1)
I am trying to pass a hyperlink in the description / artist_comments formfield using api, but Deviant displays it as a plain text url.

If I type it in manually in the description box on DA, then the text url automatically converts to html.

How do I pass on a url in my image description, so that it displays as hyperlinked url?

(I have tried using <ahref> and some [url=] shortcodes but these dont work, and show up as text codes, instead of links).

2)
Is there a way to pass on bold, paragraph, italics etc modifiers in the description / artist_comments formfield? Any html or shortcodes I use don't work. However \n works.

**Comment by sasha-lerner** [comment]
unfortunately API currently does not support rich content in any text fields including descriptions

**Comment by Neolegen** [comment]
Is there some shortcode that DeviantArt uses in their database that converts to ahref link on display?
