### ISSUE TITLE
403... Again

### ISSUE THREAD

**Issue by SomewhatDamaged** [wix-incubator/DeviantArt-API#254]
https://github.com/wix-incubator/DeviantArt-API/issues/251

Same issue as last time. 403 error:

```HTML
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: UTdnpRGOFNqWrsh-z-wVw93Pgu8slZYppLVrEf7NeHHfsCEPdeweQw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**Comment by sasha-lerner** [comment]
We can only suggest that you use IP address with better reputation
This will keep happening periodically as DDOS protection service ramps up in the response to the attacks

We are not aware how you can clear the reputation of IP address you are using

**Comment by SomewhatDamaged** [comment]
If anyone else is running into this, I have come up with a solution.

Cloudflare Warp running as a proxy.

```
warp-cli register
warp-cli proxy port <your preferred proxy port on 127.0.0.1>
warp-cli mode proxy
warp-cli connect
```

Test
`curl --proxy http://127.0.0.1:<port> https://www.cloudflare.com/cdn-cgi/trace/`
You should see `warp=on` in the reply.

Then proxy all your API/website calls through this.

For more details: https://blog.cloudflare.com/announcing-warp-for-linux-and-proxy-mode/ (note: document is a little out of date)

**Comment by Mike-E-angelo** [comment]
> We can only suggest that you use IP address with better reputation

@sasha-lerner I am hosting my application on Azure and paying the monthly fees accordingly.  Can you go into a little more detail on what you mean by this?

It would seem that you would account for the IP addresses of your registered application clients and remove them from these mitigations.  

If you have determined that the same IP addresses of your registered client applications are causing the DDoS, you should disable the client registrations rather than blocking whole swaths of IP addresses and catching innocent bystanders in the process.

I have 7 different Oauth2 providers and none of them have ever gone out of service like DeviantArt has twice now for our application over the past 2 years.  This is rather concerning obviously something you should really be improving.

**Comment by SomewhatDamaged** [comment]
@Mike-E-angelo I suspect the DDoS is more against their web traffic, rather than targeting the API. The blocking comes from their reverse-proxy service (CloudFront) and not the API itself.

As for the repeated lockouts: yeah, have lost connectivity several times in the past. Using the Warp method above gets around it since that is, effectively, a free VPN service from Cloudflare (and because it's in Proxy mode, it doesn't affect any other routing on your VPS).

Edit: Most services I work with bypass this issues by having a different service entirely host the API.

**Comment by Mike-E-angelo** [comment]
I appreciate the additional context @SomewhatDamaged.  I am not sure how effective blocking traffic/IPs are when you can simply workaround it... what's stopping the bad actors from doing the same as you have prescribed? 🤔

In any case, I am glad it's been resolved on our side for the meantime.  Onto the next fire...

**Comment by SomewhatDamaged** [comment]
@Mike-E-angelo This is me from the future! I have a solution, in case you still need it.

Cloudflare Warp is a VPN that can be run on Linux and turned into a proxy. In the last year or so, I have experienced no 403s from DeviantArt while tunneling all traffic over it.
