### ISSUE TITLE
Incorrect error for /user/whoami with client_credentials grant

### ISSUE THREAD

**Issue by KarsonOdette** [wix-incubator/DeviantArt-API#5]
When using the client_credentials grant, /user/whoami will return:
{
     "error": "invalid_token",
     "status": "error",
     "error_description": "Expired oAuth2 user token. The client should request a new one with an access code or a refresh token."
}
I believe the error should be an invalid scope error instead.
~baronbeandip~

**Comment by iamjw555559** [comment]
駭客入侵！使用錯誤令牌 數據庫！請準于改正！
